### ISSUE TITLE
Project won't compile with BME680 sensor and without ENABLE_AMBASAT_COMMANDS anymore

### ISSUE THREAD

**Issue by Need2Revolt** [michaelkamprath/ambasat1-flight-software#6]
You should enclose the implementation of 
uint8_t BME680Sensor::handleCommand(uint16_t cmdSequenceID, uint8_t command, uint8_t* recievedData, uint8_t recievedDataLen)

with

#ifdef ENABLE_AMBASAT_COMMANDS

in BME680Sensor.cpp
since also the declaration is conditional
i would make a pull request on this, but last time didn't work very well and now my fork is even farther from yours so i tought i'd point it out here...

**Comment by michaelkamprath** [comment]
Yeah, this gets fixed in @CaptainSneaker 's pull request #3 [here](https://github.com/michaelkamprath/ambasat1-flight-software/pull/3/files#diff-e25a52fc13900c6689d786d426849b53824ae6f0b6cfa8a7db38d235459d64c2R594). I haven't had a chance to do a final review yet because the day job has been crazy busy. I should get to it later this week.
